name: CI para HTML e CSS

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Verificar arquivos HTML e CSS
      run: |
        echo "Verificando HTML e CSS..."
        ls -la
